fix: Skip over duplicated functions in SymCaches
getsentry/symbolic pull request #401
Opened 2021-06-10 16:15 UTC by Swatinem

The `DwarfDebugSession::functions` Iterator can yield duplicated functions, which, combined with a ton of inlinees can blow out the `ParentOffset` limit.

This does fix the symptom of these duplicated functions, but I would say that the real fix would rather be somewhere in the Iterator that yields these values.

2021-06-11 06:29 UTC, jan-auer commented
I'll have a closer look at this PR at a later time. Just as an initial warning: Please be extremely careful with this change. IIRC, we used to have such deduplication logic and it caused issues.

2021-06-15 11:51 UTC, Swatinem commented
I moved the deduplication step into the `functions` iterator per our discussion and added a comment explaining what we *think* is going on.

Next steps:
* run the offending object through breakpads own `dump_syms`
* test electron before/after and see what the symcache differences are. electron stresses our symcache limits quite a bit

2021-06-16 07:53 UTC, jan-auer requested changes

2021-06-16 07:53 UTC, jan-auer commented on symbolic-symcache/src/writer.rs
> +            if !seen_ranges.contains(&fn_range) {
You can simplify this to:

```rust
if seen_ranges.insert(fn_range) {
  writer.add_function(function)?;
}
```

2021-06-16 07:53 UTC, jan-auer commented on symbolic-symcache/src/writer.rs
> +        let mut seen_ranges = BTreeSet::new();
Would it be enough to just track the function start address, provided that we just deal with top-level functions?

2021-06-16 07:53 UTC, jan-auer commented on symbolic-debuginfo/src/dwarf.rs
> +                if self.seen_ranges.contains(&fn_range) {
You can simplify this to:

```rust
if !self.seen_ranges.insert((func.address, func.size)) {
  continue;
}
```

2021-06-16 07:53 UTC, jan-auer commented on symbolic-debuginfo/src/dwarf.rs
> +                let fn_range = (func.address, func.size);
Would it be enough to just track the function start address, provided that we just deal with top-level functions?

2021-06-16 07:53 UTC, jan-auer commented on symbolic-debuginfo/src/dwarf.rs
> +    seen_ranges: BTreeSet<(u64, u64)>,
On second thought, MSVC may output similar duplicate entries. Can you check whether this is the case and we need to port this over, too? 

Also, I'm curious on the runtime impact on this solution. The function iterator is already quite slow due to its sorting, but we should be careful adding another _n log n_ contributor.

2021-06-16 07:53 UTC, jan-auer commented on symbolic-debuginfo/src/dwarf.rs
> +                    continue;
This check is happening too late. At this time, you have already collected the function and its full inline tree into a sorted vector. You can avoid this by pushing down `&mut seen_ranges` into `DwarfUnit::functions` a few lines below.

2021-06-16 09:07 UTC, jan-auer commented on symbolic-debuginfo/src/dwarf.rs
> +                continue;
Now, you need to set `skipped_depth = Some(depth);` before continuing. See other branches where we skip a function.

2021-06-16 13:05 UTC, jan-auer approved these changes

2021-06-16 13:05 UTC, jan-auer commented on symbolic-debuginfo/src/dwarf.rs
> +            seen_ranges: BTreeSet::new(),
_nit_: Move this before `finished`.

2021-06-16 14:14 UTC, merged