fix(debuginfo): Detect SHT_X86_64_UNWIND from gold
getsentry/symbolic pull request #505
Opened 2022-02-21 14:39 UTC by jan-auer

The `gold` linker creates `.eh_frame` and related sections with type `SHT_X86_64_UNWIND` rather than `SHT_PROGBITS`. Right now, symbolic skips those sections and as a result does not detect unwind information. 

Other than the different section type, there seem to be no differences in their content, although I yet have to verify that. 

See https://github.com/magma/magma/issues/10893

2022-02-21 21:19 UTC, mitsuhiko requested changes

2022-02-21 21:19 UTC, mitsuhiko commented on symbolic-debuginfo/src/elf.rs
> +                SHT_PROGBITS | SHT_MIPS_DWARF | SHT_X86_64_UNWIND
elfutils ran into the same thing in 2018 and changed the logic to `header.sh_type != SHT_NOBITS`. I checked the present day version (sadly the source repo cannot be linked from here) and it still retains the same logic.

I think we should align here.

2022-02-22 07:45 UTC, jan-auer commented
The linter errors still have to be fixed upstream, and before merging I would like to verify with the files provided in https://github.com/magma/magma/issues/10893#issuecomment-1044614268.

2022-02-22 08:35 UTC, Swatinem approved these changes

2022-02-22 08:39 UTC, jan-auer commented
With 431c090 it works now.

2022-02-22 09:00 UTC, mitsuhiko approved these changes

2022-02-22 16:18 UTC, merged