Avoid infinite recursion on indirect self-references
getsentry/symbolic pull request #836
Opened 2024-05-01 18:15 UTC by benjaminRomano

**Background**

If there is an indirect self-reference, infinite recursion can occur.

**Changes**
* keep track if the prior entry is the same as the next entry to go to and skip function name resolution

**Test Plan**
* tested against a symbol file where this was occurring and it no longer crashes

2024-05-02 09:35 UTC, loewenheim requested changes

2024-05-02 09:35 UTC, loewenheim commented on symbolic-debuginfo/src/dwarf.rs
> +                }
This is better with `if let`.
```suggestion
                if let Some(prior) = prior_offset {
                    if self.offset() == ref_unit.offset() && prior == ref_entry.offset() {
                        return Ok(None);
                    }
                }
```

2024-05-02 16:12 UTC, loewenheim approved these changes

2024-05-03 10:56 UTC, loewenheim commented
Nice work, would you mind adding a changelog entry?

2024-05-07 09:29 UTC, benjaminRomano commented
done

2024-05-07 09:42 UTC, merged